package assign_MDIT1;

	// Generated by Selenium IDE
//	import org.junit.Test;
//	import org.junit.Before;
//	import org.junit.After;
	//import static org.junit.Assert.*;
import static org.testng.Assert.assertEquals;
//import static org.hamcrest.CoreMatchers.is;
	//import static org.hamcrest.core.IsNot.not;
	import org.openqa.selenium.By;
	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.firefox.FirefoxDriver;
	import org.openqa.selenium.chrome.ChromeDriver;
	import org.openqa.selenium.remote.RemoteWebDriver;
	import org.openqa.selenium.remote.DesiredCapabilities;
	import org.openqa.selenium.Dimension;
	import org.openqa.selenium.WebElement;
	import org.openqa.selenium.interactions.Actions;
	import org.openqa.selenium.support.ui.ExpectedConditions;
	import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.openqa.selenium.JavascriptExecutor;
	import org.openqa.selenium.Alert;
	import org.openqa.selenium.Keys;
	import java.util.*;
	import java.net.MalformedURLException;
	import java.net.URL;
	public class Script5 {
	  private WebDriver driver;
	  private Map<String, Object> vars;
	  JavascriptExecutor js;
	  @BeforeTest
	  public void setUp() {
	    driver = new ChromeDriver();
	    js = (JavascriptExecutor) driver;
	    vars = new HashMap<String, Object>();
	  }
	  @AfterTest
	  public void tearDown() {
	    driver.quit();
	  }
	  @org.testng.annotations.Test
	  public void test1() {
	    driver.get("https://www.google.com/search?q=automation+testing+selenium&sca_esv=593778038&source=hp&ei=UOuKZc_9GPup0-kP-LqMgAU&iflsig=AO6bgOgAAAAAZYr5YEZTgUk674tfkWgkESjBfPItCZ6x&ved=0ahUKEwjP5e7or62DAxX71DQHHXgdA1AQ4dUDCAo&uact=5&oq=automation+testing+selenium&gs_lp=Egdnd3Mtd2l6IhthdXRvbWF0aW9uIHRlc3Rpbmcgc2VsZW5pdW0yBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAESLJ7UABY7nRwAHgAkAEAmAGWCaAB4jaqAQ4yLjIwLjQtMS4xLjIuMbgBA8gBAPgBAcICERAuGIAEGLEDGIMBGMcBGNEDwgIOEAAYgAQYigUYsQMYgwHCAg4QLhiABBiKBRixAxiDAcICCxAuGIAEGLEDGIMBwgIEEAAYA8ICCxAAGIAEGLEDGIMBwgIIEAAYgAQYsQPCAggQLhiABBixA8ICDhAuGIAEGLEDGMcBGNEDwgIFEC4YgATCAgsQABiABBiKBRixAw&sclient=gws-wiz");
	    
	    vars.put("c", driver.findElement(By.xpath("//a[@href=\"https://www.javatpoint.com/selenium-tutorial\"]/h3")).getText());
	    assertEquals(vars.get("c").toString(), "Selenium Tutorial");
	  }
	  @AfterTest()
	  public void at() throws InterruptedException {
	  	Thread.sleep(7000);
	  	driver.close();
	  }
	}


